site_name: Padel Counter Docs
site_url: https://padelcounter.rabid.es
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  logo: assets/raqueta-de-padel-icon.png
  favicon: assets/raqueta-de-padel-icon.png
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
nav:
  - Home: index.md
  - Recommended Setup: setup.md
  - Quick Start Guide: quickstart.md
  - Counter configuration:
    - Match Settings: counter/match.md
    - Team Select: counter/teams.md
    - Counter Screen: counter/counter.md
  - Settings:
    - General: settings/general.md
    - Controls: settings/controls.md
    - Custom Sounds: settings/custom_sounds.md
  - Help/Report an issue: help.md
extra:
  alternate:
    - name: English
      link: https://padelcounter.rabid.es
      lang: en
    - name: Spanish
      link: https://contadorpadel.rabid.es
      lang: es